In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [30]:
dataset=pd.read_csv('Data.csv')
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [31]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' nan 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 33.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' 34.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 55.0 67000.0]]


In [32]:
print(y)

['Yes' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [34]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [35]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 40.77777777777778 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 33.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 34.0 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 55.0 67000.0]]


In [36]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [37]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 40.77777777777778 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 33.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 34.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 55.0 67000.0]]


In [39]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [40]:
print(y)

[1 1 0 0 1 1 0 1 0 1]


In [42]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [43]:
print(x_train)

[[0.0 0.0 1.0 34.0 52000.0]
 [0.0 1.0 0.0 33.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 40.77777777777778 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [44]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 55.0 67000.0]]


In [45]:
print(y_train)

[0 1 1 0 1 1 0 1]


In [46]:
print(y_test)

[0 1]


In [48]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[: ,3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [49]:
print(x_train)

[[0.0 0.0 1.0 -1.0476609822388963 -1.0781259408412425]
 [0.0 1.0 0.0 -1.2127191676244553 -0.07013167641635372]
 [1.0 0.0 0.0 0.6029208716166954 0.633562432710455]
 [0.0 0.0 1.0 -0.3874282406966596 -0.30786617274297867]
 [0.0 0.0 1.0 0.07106671870767156 -1.420463615551582]
 [1.0 0.0 0.0 1.263153613158932 1.232653363453549]
 [0.0 1.0 0.0 1.5932699839300504 1.5749910381638885]
 [1.0 0.0 0.0 -0.8826027968533371 -0.5646194287757332]]


In [50]:
print(x_test)

[[0.0 1.0 0.0 -1.707893723781133 -0.9069571034860727]
 [1.0 0.0 0.0 2.4185609108578463 0.2056403393225306]]
