In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('datacountry.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[['Indonesia' 44.0 72000.0]
 ['Singapura' nan 23000.0]
 ['Indonesia' 30.0 54000.0]
 ['Malaysia' 38.0 61000.0]
 ['Thailand' 33.0 nan]
 ['Malaysia' 35.0 58000.0]
 ['Thailand' 34.0 52000.0]
 ['Indonesia' 48.0 80000.0]
 ['Vietnam' 50.0 83000.0]
 ['Vietnam' 55.0 34000.0]]


In [5]:
print(y)

['Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No']


In [6]:
from sklearn.impute import  SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['Indonesia' 44.0 72000.0]
 ['Singapura' 40.77777777777778 23000.0]
 ['Indonesia' 30.0 54000.0]
 ['Malaysia' 38.0 61000.0]
 ['Thailand' 33.0 57444.444444444445]
 ['Malaysia' 35.0 58000.0]
 ['Thailand' 34.0 52000.0]
 ['Indonesia' 48.0 80000.0]
 ['Vietnam' 50.0 83000.0]
 ['Vietnam' 55.0 34000.0]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder ='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 0.0 0.0 40.77777777777778 23000.0]
 [1.0 0.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 0.0 33.0 57444.444444444445]
 [0.0 1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 0.0 34.0 52000.0]
 [1.0 0.0 0.0 0.0 0.0 48.0 80000.0]
 [0.0 0.0 0.0 0.0 1.0 50.0 83000.0]
 [0.0 0.0 0.0 0.0 1.0 55.0 34000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[1 1 0 1 0 1 0 1 0 0]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [13]:
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 34.0 52000.0]
 [0.0 0.0 0.0 1.0 0.0 33.0 57444.444444444445]
 [1.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 0.0 40.77777777777778 23000.0]
 [1.0 0.0 0.0 0.0 0.0 48.0 80000.0]
 [0.0 0.0 0.0 0.0 1.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 35.0 58000.0]]


In [14]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 1.0 55.0 34000.0]]


In [15]:
print(y_train)

[0 0 1 1 1 1 0 1]


In [16]:
print(y_test)

[0 0]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[: ,3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 0.0 0.0 1.7320508075688774 -0.3779644730092272 -1.0476609822388963
  -0.49689267104812773]
 [0.0 0.0 0.0 1.7320508075688774 -0.3779644730092272 -1.2127191676244553
  -0.18966565677231367]
 [1.0 0.0 0.0 -0.5773502691896258 -0.3779644730092272 0.6029208716166954
  0.6316963609854748]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.3874282406966596
  0.010972393366993403]
 [0.0 0.0 1.0 -0.5773502691896258 -0.3779644730092272 0.07106671870767156
  -2.1333467674968514]
 [1.0 0.0 0.0 -0.5773502691896258 -0.3779644730092272 1.263153613158932
  1.0831319737989158]
 [0.0 0.0 0.0 -0.5773502691896258 2.6457513110645903 1.5932699839300504
  1.2524203286039561]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.8826027968533371
  -0.15831596143804696]]


In [19]:
print(x_test)

[[1.0 0.0 0.0 -0.5773502691896258 -0.3779644730092272 -1.707893723781133
  -0.38403376784476745]
 [0.0 0.0 0.0 -0.5773502691896258 2.6457513110645903 2.4185609108578463
  -1.51262279987837]]
